test:
  characters_url: http://gateway.marvel.com/v1/public/characters?
development:
  characters_url: http://gateway.marvel.com/v1/public/characters?
production:
  characters_url: http://gateway.marvel.com/v1/public/characters?